// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// BookMarkService is an autogenerated mock type for the BookMarkService type
type BookMarkService struct {
	mock.Mock
}

// GetHealthInfo provides a mock function with no fields
func (_m *BookMarkService) GetHealthInfo() (string, string) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHealthInfo")
	}

	var r0 string
	var r1 string
	if rf, ok := ret.Get(0).(func() (string, string)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() string); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(string)
	}

	return r0, r1
}

// NewBookMarkService creates a new instance of BookMarkService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBookMarkService(t interface {
	mock.TestingT
	Cleanup(func())
}) *BookMarkService {
	mock := &BookMarkService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
